services:
  db:
    image: postgres:16-alpine
    container_name: loans-service-db
    environment:
      POSTGRES_DB: loans_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"