services:
  db:
    image: postgres:16-alpine
    container_name: notifications-service-db
    environment:
      POSTGRES_DB: notifications_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
